"""empty message

Revision ID: e60a72689a0e
Revises: 
Create Date: 2022-03-06 18:24:07.858898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60a72689a0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('img', sa.String(length=250), nullable=True),
    sa.Column('nature', sa.String(length=50), nullable=b'I00\n'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nick_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eye_color', sa.String(length=40), nullable=False),
    sa.Column('skin_color', sa.String(length=40), nullable=False),
    sa.Column('birth_year', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('mass', sa.String(length=20), nullable=True),
    sa.Column('height', sa.String(length=20), nullable=True),
    sa.Column('hair_color', sa.String(length=40), nullable=False),
    sa.Column('homeworld', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'card_id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('population', sa.String(length=190), nullable=False),
    sa.Column('climate', sa.String(length=200), nullable=True),
    sa.Column('rotation_period', sa.String(length=190), nullable=True),
    sa.Column('orbital_period', sa.String(length=190), nullable=True),
    sa.Column('diameter', sa.String(length=200), nullable=True),
    sa.Column('terrain', sa.String(length=200), nullable=True),
    sa.Column('gravity', sa.String(length=200), nullable=True),
    sa.Column('surface_water', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('passengers', sa.String(length=200), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=200), nullable=True),
    sa.Column('length', sa.String(length=230), nullable=True),
    sa.Column('consumables', sa.String(length=230), nullable=True),
    sa.Column('starship_class', sa.String(length=230), nullable=True),
    sa.Column('manufacturer', sa.String(length=230), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=230), nullable=True),
    sa.Column('crew', sa.String(length=230), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=230), nullable=True),
    sa.Column('hyperdrive_rating', sa.String(length=230), nullable=True),
    sa.Column('MGLT', sa.String(length=230), nullable=True),
    sa.Column('pilots', sa.String(length=230), nullable=True),
    sa.Column('url', sa.String(length=230), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('planet')
    op.drop_table('favorite')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('card')
    # ### end Alembic commands ###
